"""
Retrospective Engine — Self-learning from interaction logs.

Jarvis reads its own daily logs, detects misclassifications,
and auto-generates fixes that are loaded on next startup.

Detection signals:
    1. User repeated themselves (similar command 2x within 3 turns)
    2. Fast engine != Gemini resolution (disagreement)
    3. Low confidence (<0.50) + wrong action
    4. Action result started with "Error" or "Couldn't find"
    5. User started with "no" (explicit rejection of previous action)

Fix generation:
    - Asks Gemini: "Given this command, what is the correct intent?"
    - Generates generalized examples (not just the exact phrase)
    - Stores as patches in data/intent_patches.json
    - Also stores error corrections in data/error_corrections.json
    - Generates a learning report in data/learning_reports/

Cross-platform: Pure Python, JSON I/O.
"""

import os
import json
import time
import re
from datetime import datetime, timedelta
from typing import Optional, List
from dataclasses import dataclass, asdict


# ─── Settings ────────────────────────────────────────────────
BASE_DIR       = os.path.dirname(os.path.dirname(__file__))
LOGS_DIR       = os.path.join(BASE_DIR, "logs")
PATCHES_PATH   = os.path.join(BASE_DIR, "data", "intent_patches.json")
REPORTS_DIR    = os.path.join(BASE_DIR, "data", "learning_reports")
MAX_FIXES_PER_REVIEW = 15   # Cap Gemini calls per review session
# ─────────────────────────────────────────────────────────────


# All known valid actions (for validation)
VALID_ACTIONS = {
    "open_app", "close_app", "switch_to_app", "minimise_app",
    "volume_up", "volume_down", "mute", "unmute", "get_volume",
    "brightness_up", "brightness_down",
    "lock_screen", "shutdown_pc", "restart_pc", "sleep_mac",
    "take_screenshot", "get_battery",
    "tell_time", "tell_date", "tell_weather",
    "search_google", "web_search",
    "open_url", "web_back", "web_refresh", "web_new_tab", "web_close_tab",
    "open_folder", "create_folder", "search_file",
    "read_emails", "search_emails", "send_email", "open_gmail",
    "minimise_all", "show_desktop", "close_window", "close_tab",
    "new_tab", "fullscreen", "mission_control",
    "start_work_day", "end_work_day", "morning_briefing", "read_news",
    "summarise_pdf",
    "answer_question", "general_chat",
    "read_file", "create_file", "edit_file", "create_and_edit_file",
    "delete_file", "rename_file", "copy_file", "get_recent_files",
    "play_song", "play_mood_music",
    "save_note", "append_note", "search_vault",
}


@dataclass
class DetectedMistake:
    """A detected misclassification from log analysis."""
    command:           str       # What the user said
    wrong_action:      str       # What was executed (incorrectly)
    wrong_confidence:  float     # Confidence of the wrong action
    correct_action:    str = ""  # What it should have been (if known)
    signal:            str = ""  # Why we think it's wrong
    timestamp:         str = ""
    log_index:         int = 0   # Position in the day's log


@dataclass
class GeneratedFix:
    """A fix generated by Gemini analysis."""
    correct_action:    str
    add_examples:      list       # Generalized examples to add
    wrong_action:      str = ""   # What it was misrouted as
    original_command:  str = ""
    negative_example:  str = ""   # "this command is NOT this action"
    confidence:        float = 1.0


class RetrospectiveEngine:
    """
    Self-learning engine that reviews daily logs and generates fixes.

    Usage:
        engine = RetrospectiveEngine()
        report = engine.review_yesterday()
        # or
        report = engine.review_day("2026-04-18")
    """

    def __init__(self):
        os.makedirs(REPORTS_DIR, exist_ok=True)

    def review_yesterday(self) -> dict:
        """Review yesterday's logs and apply fixes."""
        yesterday = (datetime.now() - timedelta(days=1)).strftime("%Y-%m-%d")
        return self.review_day(yesterday)

    def review_today(self) -> dict:
        """Review today's logs (useful for end-of-session review)."""
        today = datetime.now().strftime("%Y-%m-%d")
        return self.review_day(today)

    def review_day(self, date: str) -> dict:
        """
        Full retrospective review for a given date.

        Steps:
            1. Load log entries
            2. Detect mistakes
            3. Generate fixes via Gemini
            4. Apply fixes to intent_patches.json
            5. Generate learning report

        Returns:
            Report dict with stats and fixes applied.
        """
        log_path = os.path.join(LOGS_DIR, f"{date}.json")
        if not os.path.exists(log_path):
            print(f"[R] No logs found for {date}")
            return {"date": date, "status": "no_logs", "mistakes": 0, "fixes": 0}

        try:
            with open(log_path, "r", encoding="utf-8") as f:
                entries = json.load(f)
        except Exception as e:
            print(f"[R] Error reading logs: {e}")
            return {"date": date, "status": "error", "error": str(e)}

        if not entries:
            return {"date": date, "status": "empty", "mistakes": 0, "fixes": 0}

        print(f"\n[R] Reviewing {len(entries)} interactions from {date}...")

        # ── Step 1: Detect mistakes ─────────────────────────
        mistakes = self._detect_all(entries)
        print(f"[R] Detected {len(mistakes)} potential mistakes")

        if not mistakes:
            return {"date": date, "status": "clean", "mistakes": 0, "fixes": 0}

        # ── Step 2: Generate fixes via Gemini ────────────────
        fixes = []
        for mistake in mistakes[:MAX_FIXES_PER_REVIEW]:
            fix = self._generate_fix(mistake)
            if fix:
                fixes.append(fix)

        print(f"[R] Generated {len(fixes)} fixes")

        # ── Step 3: Apply fixes ──────────────────────────────
        if fixes:
            self._apply_fixes(fixes)
            self._apply_error_corrections(fixes)
            print(f"[R] Applied {len(fixes)} patches")

        # ── Step 4: Generate report ──────────────────────────
        report = {
            "date":      date,
            "status":    "reviewed",
            "total_entries": len(entries),
            "mistakes":  len(mistakes),
            "fixes":     len(fixes),
            "details":   [asdict(m) for m in mistakes],
            "fixes_applied": [asdict(f) for f in fixes],
            "reviewed_at": datetime.now().isoformat(),
        }

        self._save_report(date, report)

        return report

    # ─── Detection Engine ────────────────────────────────────

    def _detect_all(self, entries: list) -> list:
        """Run all detection signals on log entries."""
        mistakes = []

        # Signal 1: User repeated themselves
        mistakes.extend(self._detect_repetition(entries))

        # Signal 2: Fast engine != Gemini
        mistakes.extend(self._detect_fast_vs_gemini(entries))

        # Signal 3: Failures
        mistakes.extend(self._detect_failures(entries))

        # Signal 4: Low confidence wrong actions
        mistakes.extend(self._detect_low_confidence(entries))

        # Signal 5: User said "no" after an action
        mistakes.extend(self._detect_rejection(entries))

        # Deduplicate by command
        seen = set()
        unique = []
        for m in mistakes:
            key = m.command.lower().strip()
            if key not in seen:
                seen.add(key)
                unique.append(m)

        return unique

    def _detect_repetition(self, entries: list) -> list:
        """
        Detect when user said similar things 2+ times in a row.
        This means the first attempt failed to understand them.
        """
        mistakes = []

        for i in range(1, len(entries)):
            curr = entries[i]
            prev = entries[i - 1]

            curr_text = (curr.get("normalized") or curr.get("you_said", "")).lower()
            prev_text = (prev.get("normalized") or prev.get("you_said", "")).lower()

            if not curr_text or not prev_text:
                continue

            # Check word overlap
            overlap = self._word_overlap(curr_text, prev_text)

            if overlap > 0.5 and curr.get("action_taken") != prev.get("action_taken"):
                # User repeated but got different actions → first one was wrong
                mistakes.append(DetectedMistake(
                    command=prev.get("you_said", ""),
                    wrong_action=prev.get("action_taken", ""),
                    wrong_confidence=prev.get("confidence", 0),
                    correct_action=curr.get("action_taken", ""),
                    signal="repetition",
                    timestamp=prev.get("timestamp", ""),
                    log_index=i - 1,
                ))

        return mistakes

    def _detect_fast_vs_gemini(self, entries: list) -> list:
        """
        Detect where fast engine classified one way but Gemini resolved differently.
        Gemini is usually right in these cases.
        """
        mistakes = []

        for i, entry in enumerate(entries):
            if not entry.get("sent_to_gemini"):
                continue

            # If Gemini was called and took a DIFFERENT action
            fast_action = entry.get("action_taken", "")
            gemini_resp = entry.get("gemini_response", "")

            # The action_taken is the FINAL action (which may be Gemini's)
            # If intent_source is "gemini", then fast engine got it wrong
            if entry.get("intent_source") == "gemini":
                # We need to figure out what the fast engine thought
                conf = entry.get("confidence", 0)
                if conf and conf < 0.55:
                    # Low confidence fallback to Gemini — this is a learning opportunity
                    mistakes.append(DetectedMistake(
                        command=entry.get("you_said", ""),
                        wrong_action="unknown_fast",
                        wrong_confidence=conf,
                        correct_action=fast_action,  # Gemini's action is correct
                        signal="gemini_fallback",
                        timestamp=entry.get("timestamp", ""),
                        log_index=i,
                    ))

        return mistakes

    def _detect_failures(self, entries: list) -> list:
        """Detect actions that resulted in errors."""
        mistakes = []

        for i, entry in enumerate(entries):
            error = entry.get("error", "")
            you_said = entry.get("you_said", "")

            if not error and not you_said:
                continue

            # Check if the logged action result indicates failure
            # We look for patterns like "Couldn't find app: X"
            action = entry.get("action_taken", "")
            if action and action.endswith("_cancelled"):
                continue  # User cancelled — not a mistake

            if error:
                mistakes.append(DetectedMistake(
                    command=you_said,
                    wrong_action=action,
                    wrong_confidence=entry.get("confidence", 0),
                    signal="error_result",
                    timestamp=entry.get("timestamp", ""),
                    log_index=i,
                ))

        return mistakes

    def _detect_low_confidence(self, entries: list) -> list:
        """Detect low confidence actions that seem wrong based on heuristics."""
        mistakes = []

        for i, entry in enumerate(entries):
            conf = entry.get("confidence", 1.0)
            action = entry.get("action_taken", "")
            command = entry.get("you_said", "")

            if not command or conf is None:
                continue

            # Low confidence + heuristic mismatch detection
            if conf < 0.50 and entry.get("intent_source") == "builtin":
                # Check for obvious mismatches
                cmd_lower = command.lower()

                # "what's on my screen" → should NOT be brightness
                if ("screen" in cmd_lower and "see" in cmd_lower and
                        action in ("brightness_up", "brightness_down")):
                    mistakes.append(DetectedMistake(
                        command=command,
                        wrong_action=action,
                        wrong_confidence=conf,
                        correct_action="take_screenshot",
                        signal="heuristic_mismatch",
                        timestamp=entry.get("timestamp", ""),
                        log_index=i,
                    ))
                # "tell me about X" → should NOT be open_app
                elif ("tell me" in cmd_lower and "about" in cmd_lower and
                      action == "open_app"):
                    mistakes.append(DetectedMistake(
                        command=command,
                        wrong_action=action,
                        wrong_confidence=conf,
                        correct_action="answer_question",
                        signal="heuristic_mismatch",
                        timestamp=entry.get("timestamp", ""),
                        log_index=i,
                    ))
                # Generic low confidence
                elif conf < 0.40:
                    mistakes.append(DetectedMistake(
                        command=command,
                        wrong_action=action,
                        wrong_confidence=conf,
                        signal="low_confidence",
                        timestamp=entry.get("timestamp", ""),
                        log_index=i,
                    ))

        return mistakes

    def _detect_rejection(self, entries: list) -> list:
        """Detect when user said 'no' right after an action."""
        mistakes = []

        for i in range(1, len(entries)):
            curr_text = (entries[i].get("you_said") or "").lower().strip()

            if curr_text.startswith("no ") or curr_text == "no":
                prev = entries[i - 1]
                mistakes.append(DetectedMistake(
                    command=prev.get("you_said", ""),
                    wrong_action=prev.get("action_taken", ""),
                    wrong_confidence=prev.get("confidence", 0),
                    signal="user_rejection",
                    timestamp=prev.get("timestamp", ""),
                    log_index=i - 1,
                ))

        return mistakes

    # ─── Fix Generation ──────────────────────────────────────

    def _generate_fix(self, mistake: DetectedMistake) -> Optional[GeneratedFix]:
        """
        Ask Gemini to determine the correct intent and generate
        generalized training examples.
        """
        # If we already know the correct action, skip Gemini call
        if mistake.correct_action and mistake.correct_action in VALID_ACTIONS:
            return self._generate_examples_for(
                mistake.command,
                mistake.correct_action,
                mistake.wrong_action,
            )

        # Ask Gemini
        try:
            correct_action = self._ask_gemini_correct_intent(mistake.command)
            if correct_action and correct_action in VALID_ACTIONS:
                return self._generate_examples_for(
                    mistake.command,
                    correct_action,
                    mistake.wrong_action,
                )
        except Exception as e:
            print(f"[R] Gemini fix generation failed: {e}")

        return None

    def _ask_gemini_correct_intent(self, command: str) -> Optional[str]:
        """Ask Gemini what the correct intent is for a command."""
        try:
            from google import genai
            import dotenv
            dotenv.load_dotenv()

            client = genai.Client(api_key=os.getenv("API_KEY"))

            actions_list = ", ".join(sorted(VALID_ACTIONS))

            prompt = f"""You are an intent classifier for a voice assistant called Jarvis.

Given this user command: "{command}"

What is the correct intent/action from this list?
{actions_list}

Return ONLY the action name, nothing else. Example: take_screenshot"""

            response = client.models.generate_content(
                model="gemini-3.1-flash-lite-preview",
                contents=prompt,
            )

            action = response.text.strip().lower().replace('"', '').replace("'", "")
            # Clean up common response patterns
            action = action.split('\n')[0].strip()
            action = action.split(' ')[0].strip() if ' ' in action else action

            if action in VALID_ACTIONS:
                return action

            # Try fuzzy match
            for valid in VALID_ACTIONS:
                if valid in action:
                    return valid

            print(f"[R] Gemini returned invalid action: {action}")
            return None

        except Exception as e:
            print(f"[R] Gemini call failed: {e}")
            return None

    def _generate_examples_for(
        self,
        original_command: str,
        correct_action: str,
        wrong_action: str,
    ) -> GeneratedFix:
        """Generate generalized examples from an original command."""
        # Generate variations of the command
        examples = self._generalize_command(original_command, correct_action)

        return GeneratedFix(
            correct_action=correct_action,
            add_examples=examples,
            wrong_action=wrong_action,
            original_command=original_command,
            negative_example=original_command if wrong_action else "",
        )

    def _generalize_command(self, command: str, action: str) -> list:
        """
        Generate generalized variations of a command.
        Uses pattern-based generation (no Gemini call needed).
        """
        cmd = command.lower().strip()
        examples = [cmd]

        # Remove filler words to create a cleaner version
        fillers = ["can you", "could you", "please", "just",
                   "right now", "for me", "man", "bro", "dude",
                   "you know", "basically", "actually", "like"]
        clean = cmd
        for filler in fillers:
            clean = clean.replace(filler, "").strip()
        clean = re.sub(r'\s+', ' ', clean).strip()

        if clean != cmd and len(clean) > 3:
            examples.append(clean)

        # Create a short version (first 5 meaningful words)
        words = [w for w in clean.split() if len(w) > 1]
        if len(words) > 4:
            short = " ".join(words[:5])
            if short != clean:
                examples.append(short)

        # Remove leading "no " if present (from rejection detection)
        if cmd.startswith("no "):
            without_no = cmd[3:].strip()
            if without_no and without_no not in examples:
                examples.append(without_no)

        # Deduplicate and limit
        seen = set()
        unique = []
        for e in examples:
            if e not in seen and len(e) > 3:
                seen.add(e)
                unique.append(e)

        return unique[:5]  # Max 5 examples per fix

    # ─── Fix Application ─────────────────────────────────────

    def _apply_fixes(self, fixes: list) -> None:
        """Apply fixes to data/intent_patches.json."""
        # Load existing patches
        existing = {"generated": "", "patches": [], "negative_examples": []}
        if os.path.exists(PATCHES_PATH):
            try:
                with open(PATCHES_PATH, "r", encoding="utf-8") as f:
                    existing = json.load(f)
            except Exception:
                pass

        existing["generated"] = datetime.now().strftime("%Y-%m-%d")

        # Merge new patches
        existing_actions = {}
        for patch in existing.get("patches", []):
            action = patch.get("action", "")
            if action:
                existing_actions[action] = patch

        for fix in fixes:
            if fix.correct_action in existing_actions:
                # Merge examples
                patch = existing_actions[fix.correct_action]
                existing_set = set(patch.get("add_examples", []))
                new_examples = [e for e in fix.add_examples
                               if e not in existing_set]
                patch["add_examples"].extend(new_examples)
            else:
                # New patch
                patch = {
                    "action": fix.correct_action,
                    "add_examples": fix.add_examples,
                    "source": "retrospective",
                    "from_command": fix.original_command,
                    "was_misrouted_as": fix.wrong_action,
                }
                existing["patches"].append(patch)
                existing_actions[fix.correct_action] = patch

            # Add negative example
            if fix.negative_example and fix.wrong_action:
                existing.setdefault("negative_examples", []).append({
                    "action": fix.wrong_action,
                    "text": fix.negative_example,
                    "correct_action": fix.correct_action,
                })

        # Rebuild patches list from merged dict
        existing["patches"] = list(existing_actions.values())

        # Save
        os.makedirs(os.path.dirname(PATCHES_PATH), exist_ok=True)
        with open(PATCHES_PATH, "w", encoding="utf-8") as f:
            json.dump(existing, f, indent=2, ensure_ascii=False)

        print(f"[R] Saved {len(existing['patches'])} total patches "
              f"to intent_patches.json")

    def _apply_error_corrections(self, fixes: list) -> None:
        """Also store fixes as error corrections for immediate override."""
        try:
            from core.error_correction import get_error_correction_store
            store = get_error_correction_store()

            for fix in fixes:
                if fix.wrong_action and fix.correct_action != fix.wrong_action:
                    store.learn_intent_correction(
                        wrong_intent=fix.wrong_action,
                        correct_intent=fix.correct_action,
                        original_command=fix.original_command,
                        context="retrospective",
                    )
        except Exception as e:
            print(f"[R] Error correction storage failed: {e}")

    # ─── Reporting ───────────────────────────────────────────

    def _save_report(self, date: str, report: dict) -> None:
        """Save a learning report for review."""
        report_path = os.path.join(REPORTS_DIR, f"report_{date}.json")
        os.makedirs(REPORTS_DIR, exist_ok=True)

        with open(report_path, "w", encoding="utf-8") as f:
            json.dump(report, f, indent=2, ensure_ascii=False)

        print(f"[R] Learning report saved: {report_path}")

        # Also print a summary
        print(f"\n{'=' * 50}")
        print(f"  RETROSPECTIVE REPORT — {date}")
        print(f"{'=' * 50}")
        print(f"  Total interactions:  {report['total_entries']}")
        print(f"  Mistakes detected:   {report['mistakes']}")
        print(f"  Fixes applied:       {report['fixes']}")

        if report.get("fixes_applied"):
            print(f"\n  Fixes:")
            for fix in report["fixes_applied"]:
                print(f"    {fix['wrong_action']} -> {fix['correct_action']}")
                print(f"      Command: \"{fix['original_command']}\"")
                print(f"      Examples: {fix['add_examples']}")

        print(f"{'=' * 50}\n")

    # ─── Helpers ─────────────────────────────────────────────

    def _word_overlap(self, a: str, b: str) -> float:
        """Jaccard word overlap between two strings."""
        words_a = set(a.lower().split())
        words_b = set(b.lower().split())
        if not words_a or not words_b:
            return 0.0
        intersection = words_a & words_b
        union = words_a | words_b
        return len(intersection) / len(union) if union else 0.0


# ─── Public API ──────────────────────────────────────────────

def run_retrospective(date: str = None) -> dict:
    """
    Run retrospective review. Called from main.py on startup.

    Args:
        date: Date to review (YYYY-MM-DD). Defaults to yesterday.

    Returns:
        Report dict.
    """
    engine = RetrospectiveEngine()
    if date:
        return engine.review_day(date)
    else:
        return engine.review_yesterday()


# ─── Quick Test ──────────────────────────────────────────────
if __name__ == "__main__":
    print("=" * 60)
    print("  RETROSPECTIVE ENGINE TEST")
    print("=" * 60)

    engine = RetrospectiveEngine()

    # Create sample log data that simulates the bugs from bugs.txt
    sample_entries = [
        {
            "timestamp": "2026-04-18 22:39:00",
            "you_said": "can you tell me what am i seeing on my screen right now",
            "normalized": "can you tell me what am i seeing on my screen",
            "action_taken": "brightness_up",
            "was_understood": True,
            "intent_source": "builtin",
            "confidence": 0.48,
            "latency_ms": 4339,
        },
        {
            "timestamp": "2026-04-18 22:39:30",
            "you_said": "no can you tell me what is there on my screen right now",
            "normalized": "no can you tell me what is there on my screen",
            "action_taken": "take_screenshot",
            "was_understood": True,
            "sent_to_gemini": True,
            "intent_source": "gemini",
            "confidence": 0.44,
            "latency_ms": 9188,
        },
        {
            "timestamp": "2026-04-18 22:42:00",
            "you_said": "let me all the details regarding the open claw what is open claw",
            "normalized": "let me all the details regarding the open claw what is open claw",
            "action_taken": "open_app",
            "was_understood": True,
            "intent_source": "builtin",
            "confidence": 0.46,
            "latency_ms": 10794,
        },
        {
            "timestamp": "2026-04-18 22:45:00",
            "you_said": "what all conversations did we have till now",
            "normalized": "what all conversations did we have till now",
            "action_taken": "morning_briefing",
            "was_understood": True,
            "intent_source": "builtin",
            "confidence": 0.37,
            "latency_ms": 5000,
        },
    ]

    print("\n-- Detecting mistakes from sample data --")
    mistakes = engine._detect_all(sample_entries)
    for m in mistakes:
        print(f"  [{m.signal}] \"{m.command[:50]}\" -> {m.wrong_action} "
              f"(conf={m.wrong_confidence:.2f})"
              f"{f' -> should be {m.correct_action}' if m.correct_action else ''}")

    print(f"\n  Total mistakes: {len(mistakes)}")

    # Test generalization
    print("\n-- Testing example generalization --")
    examples = engine._generalize_command(
        "can you tell me what am i seeing on my screen right now",
        "take_screenshot"
    )
    print(f"  Generated {len(examples)} examples:")
    for e in examples:
        print(f"    - \"{e}\"")

    examples2 = engine._generalize_command(
        "no can you tell me what is there on my screen right now",
        "take_screenshot"
    )
    print(f"\n  Generated {len(examples2)} examples (from 'no' rejection):")
    for e in examples2:
        print(f"    - \"{e}\"")

    print("\nDone. (Skipped Gemini calls + patch application in test mode)")
    print("Run 'python -m core.retrospective --review today' for a live review.")
